# Generated by Django 5.2.7 on 2025-11-13 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Категория',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('описание', models.TextField(blank=True, verbose_name='Описание')),
                ('изображение', models.CharField(blank=True, max_length=500, verbose_name='Изображение категории')),
                ('иконка', models.CharField(default='🍽️', max_length=50, verbose_name='Иконка')),
                ('активно', models.BooleanField(default=True, verbose_name='Активна')),
                ('теги', models.JSONField(default=list, verbose_name='Теги категории')),
                ('создано', models.DateTimeField(auto_now_add=True)),
                ('обновлено', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'категории',
                'ordering': ['название'],
            },
        ),
        migrations.CreateModel(
            name='Промокод',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('код', models.CharField(max_length=20, unique=True)),
                ('описание', models.TextField(blank=True)),
                ('скидка', models.IntegerField(verbose_name='Скидка в %')),
                ('минимальная_сумма', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('активно', models.BooleanField(default=True)),
                ('срок_действия', models.DateTimeField()),
                ('использовано', models.IntegerField(default=0)),
                ('создано', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'db_table': 'промокоды',
            },
        ),
        migrations.CreateModel(
            name='Заказ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('статус', models.CharField(choices=[('новый', '🆕 Новый'), ('подтвержден', '✅ Подтвержден'), ('готовится', '👨\u200d🍳 Готовится'), ('готов', '📦 Готов к выдаче'), ('выполнен', '🎉 Выполнен'), ('отменен', '❌ Отменен')], default='новый', max_length=20)),
                ('общая_сумма', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('имя_клиента', models.CharField(max_length=100)),
                ('телефон', models.CharField(max_length=20)),
                ('адрес', models.TextField(blank=True)),
                ('комментарий', models.TextField(blank=True)),
                ('способ_оплаты', models.CharField(choices=[('наличные', 'Наличные'), ('карта', 'Карта'), ('онлайн', 'Онлайн')], default='наличные', max_length=50)),
                ('создано', models.DateTimeField(auto_now_add=True)),
                ('обновлено', models.DateTimeField(auto_now=True)),
                ('пользователь', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='заказы', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'заказы',
                'ordering': ['-создано'],
            },
        ),
        migrations.CreateModel(
            name='Блюдо',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('тип_блюда', models.CharField(choices=[('закуска', 'Закуска'), ('салат', 'Салат'), ('суп', 'Суп'), ('основное', 'Основное блюдо'), ('десерт', 'Десерт'), ('напиток', 'Напиток')], default='основное', max_length=20)),
                ('название', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('описание', models.TextField(blank=True, verbose_name='Описание')),
                ('цена', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('изображение', models.CharField(blank=True, max_length=500, verbose_name='Ссылка на изображение')),
                ('вес_объем', models.CharField(max_length=50, verbose_name='Вес/Объем')),
                ('состав', models.TextField(verbose_name='Состав')),
                ('пищевая_ценность', models.JSONField(default=dict, verbose_name='Пищевая ценность')),
                ('время_приготовления', models.PositiveIntegerField(default=15, verbose_name='Время приготовления (мин)')),
                ('уровень_остроты', models.PositiveIntegerField(choices=[(0, 'Не острое'), (1, 'Слабо острое'), (2, 'Средне острое'), (3, 'Острое'), (4, 'Очень острое')], default=0)),
                ('теги', models.JSONField(default=list)),
                ('активно', models.BooleanField(default=True)),
                ('акция', models.BooleanField(default=False)),
                ('цена_со_скидкой', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('популярность', models.IntegerField(default=0)),
                ('создано', models.DateTimeField(auto_now_add=True)),
                ('обновлено', models.DateTimeField(auto_now=True)),
                ('категория', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='блюда', to='first_app.категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'db_table': 'блюда',
                'ordering': ['-популярность', 'название'],
            },
        ),
        migrations.CreateModel(
            name='Корзина',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('создано', models.DateTimeField(auto_now_add=True)),
                ('обновлено', models.DateTimeField(auto_now=True)),
                ('пользователь', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='корзина', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'db_table': 'корзины',
            },
        ),
        migrations.CreateModel(
            name='Профиль',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('телефон', models.CharField(blank=True, max_length=20)),
                ('адрес', models.TextField(blank=True)),
                ('дата_рождения', models.DateField(blank=True, null=True)),
                ('предпочтения', models.JSONField(default=dict)),
                ('аватар', models.CharField(blank=True, max_length=500)),
                ('создано', models.DateTimeField(auto_now_add=True)),
                ('обновлено', models.DateTimeField(auto_now=True)),
                ('пользователь', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='профиль', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'профили',
            },
        ),
        migrations.CreateModel(
            name='ЭлементЗаказа',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('количество', models.PositiveIntegerField(default=1)),
                ('цена_на_момент', models.DecimalField(decimal_places=2, max_digits=10)),
                ('блюдо', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.блюдо')),
                ('заказ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='элементы', to='first_app.заказ')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
                'db_table': 'элементы_заказа',
            },
        ),
        migrations.CreateModel(
            name='Избранное',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('добавлено', models.DateTimeField(auto_now_add=True)),
                ('блюдо', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.блюдо')),
                ('пользователь', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='избранное', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'db_table': 'избранное',
                'unique_together': {('пользователь', 'блюдо')},
            },
        ),
        migrations.CreateModel(
            name='Отзыв',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('рейтинг', models.PositiveIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')])),
                ('комментарий', models.TextField(blank=True)),
                ('создано', models.DateTimeField(auto_now_add=True)),
                ('обновлено', models.DateTimeField(auto_now=True)),
                ('блюдо', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='отзывы', to='first_app.блюдо')),
                ('пользователь', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='отзывы', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'отзывы',
                'ordering': ['-создано'],
                'unique_together': {('пользователь', 'блюдо')},
            },
        ),
        migrations.CreateModel(
            name='ЭлементКорзины',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('количество', models.PositiveIntegerField(default=1)),
                ('добавлено', models.DateTimeField(auto_now_add=True)),
                ('блюдо', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.блюдо')),
                ('корзина', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='элементы', to='first_app.корзина')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
                'db_table': 'элементы_корзины',
                'unique_together': {('корзина', 'блюдо')},
            },
        ),
    ]
